apiVersion: v1
kind: Pod
metadata:
  name: training-application
spec:
  containers:
    - name: training-application
      image: quay.io/kubermatic-labs/training-application:3.0.0
      imagePullPolicy: Always
      tty: true
      stdin: true
      ports:
        - name: http
          containerPort: 8080
