FROM golang:1.24.3-alpine AS builder
WORKDIR /src
COPY src/go.mod src/go.sum ./
RUN go mod download
COPY src/*.go src/root.html ./
RUN CGO_ENABLED=0 go build -o training-application

FROM gcr.io/distroless/static-debian12
COPY --from=builder /src/training-application /
COPY training-application.conf /
ENTRYPOINT [ "/training-application" ]
