name: Build and Push Training Application Images

on:
  push:
    branches:
      - "main"
    paths:
      - src/**
      - docker/**
      - training-application.conf
      - makefile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # - name: Lint application
      #   run: make lint
      - name: Build application
        run: make build
      # - name: Lint Dockerfiles
      #   run: make docker-lint
      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Push all Docker Images
        run: make docker-push-all
