name: Build and Push Training Application Helm Chart

on:
  push:
    branches:
      - "main"
    paths:
      - helm-chart/**
      - makefile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Install Helm
        uses: azure/setup-helm@v4.3.0
      - name: Push Helm Chart
        run: make helm-push
